# Generated by Django 5.0.3 on 2024-04-07 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
        ('common', '0003_connectiontype_country_support_alter_usercar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='last_status_reason',
            field=models.CharField(choices=[('normal', 'Normal'), ('charger_disconnected', 'Charge Disconnected'), ('manual', 'Manual')], db_default='normal', default='normal', max_length=30, verbose_name='Last status reason'),
        ),
        migrations.AlterField(
            model_name='chargingtransaction',
            name='meter_used',
            field=models.FloatField(default=0, verbose_name='Meter Used'),
        ),
        migrations.AlterField(
            model_name='chargingtransaction',
            name='start_reason',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Remote', 'Remote')], max_length=40, null=True, verbose_name='Start Reason'),
        ),
        migrations.AlterField(
            model_name='chargingtransaction',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=40, null=True, verbose_name='Stop Reason'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEVSE', 'Suspended Evse'), ('SuspendedEV', 'Suspended Ev'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='Unavailable', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ChargeCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('command', models.CharField(choices=[('REMOTE_START_TRANSACTION', 'Remote start transaction'), ('REMOTE_STOP_TRANSACTION', 'Remote start transaction')], max_length=50, verbose_name='Command')),
                ('id_tag', models.CharField(max_length=20, verbose_name='Unique Id tag of command')),
                ('is_delivered', models.BooleanField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chargers.connector', verbose_name='Connector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.usercar', verbose_name='User Car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
