# Generated by Django 5.0.3 on 2024-04-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_connector_last_status_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargepoint',
            options={'ordering': ['-id'], 'verbose_name': 'Charge Point', 'verbose_name_plural': 'Charge Points'},
        ),
    ]
