# Generated by Django 5.0.3 on 2024-04-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0003_alter_chargepoint_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargepoint",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chargers",
                to="chargers.location",
                verbose_name="Location",
            ),
        ),
    ]
