# Generated by Django 5.0.3 on 2024-04-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0004_alter_chargepoint_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="charge_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connectors",
                to="chargers.chargepoint",
                verbose_name="Charge Point",
            ),
        ),
    ]
