# Generated by Django 5.0.3 on 2024-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0006_alter_chargingtransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingtransaction',
            name='battery_percent_on_start',
            field=models.IntegerField(db_default=0, verbose_name='Battery Percent on Start'),
        ),
    ]
