# Generated by Django 5.0.3 on 2024-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0007_alter_chargingtransaction_battery_percent_on_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecommand',
            name='is_limited',
            field=models.BooleanField(db_default=False),
        ),
        migrations.AddField(
            model_name='chargecommand',
            name='limited_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limited Money'),
        ),
        migrations.AddField(
            model_name='chargingtransaction',
            name='limited_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limited Money'),
        ),
    ]
