# Generated by Django 5.0.3 on 2024-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0009_alter_chargecommand_limited_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingtransaction',
            name='battery_percent_on_end',
            field=models.IntegerField(db_default=0, verbose_name='Battery Percent on End'),
        ),
    ]
