# Generated by Django 5.0.3 on 2024-04-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0010_alter_chargingtransaction_battery_percent_on_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedChargingTransactionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Finished Charging Transaction',
                'verbose_name_plural': 'Finished Charging Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chargers.chargingtransaction',),
        ),
        migrations.CreateModel(
            name='InProgressChargingTransactionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'In Progress Charging Transaction',
                'verbose_name_plural': 'In Progress Charging Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chargers.chargingtransaction',),
        ),
    ]
