# Generated by Django 5.0.3 on 2024-04-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0012_alter_chargingtransaction_stop_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecommand',
            name='initiator',
            field=models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], db_default='USER', editable=False, max_length=50, verbose_name='Initiator'),
        ),
    ]
