# Generated by Django 5.0.3 on 2024-05-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0013_chargecommand_initiator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
