# Generated by Django 5.0.3 on 2024-05-03 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0014_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingtransaction',
            name='start_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_command_transaction', to='chargers.chargecommand', verbose_name='Start Command'),
        ),
    ]
