# Generated by Django 5.0.3 on 2024-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0015_chargingtransaction_start_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCPPServiceRequestResponseLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('charger_id', models.CharField(max_length=50, verbose_name='Charger ID')),
                ('request_action', models.CharField(max_length=50, verbose_name='Request Action')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Response')),
            ],
            options={
                'verbose_name': 'OCPP Service Request Response Log',
                'verbose_name_plural': 'OCPP Service Request Response Logs',
                'ordering': ['-id'],
            },
        ),
    ]
