# Generated by Django 5.0.3 on 2024-05-12 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0017_chargepoint_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chargepoint",
            options={
                "ordering": ["order"],
                "verbose_name": "Charge Point",
                "verbose_name_plural": "Charge Points",
            },
        ),
    ]
