# Generated by Django 5.0.3 on 2024-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0018_alter_chargepoint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingtransaction',
            name='battery_percent_on_end',
            field=models.IntegerField(db_default=0, default=0, verbose_name='Battery Percent on End'),
        ),
        migrations.AlterField(
            model_name='chargingtransaction',
            name='battery_percent_on_start',
            field=models.IntegerField(db_default=0, default=0, verbose_name='Battery Percent on Start'),
        ),
    ]
