# Generated by Django 5.0.3 on 2024-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0019_alter_chargingtransaction_battery_percent_on_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='price_per_kwh',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10, verbose_name='Price for 1 kwt of electricity'),
        ),
        migrations.AddField(
            model_name='chargingtransaction',
            name='price_per_kwh',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10, verbose_name='Price for 1 kwt of electricity'),
        ),
        migrations.AlterField(
            model_name='chargecommand',
            name='command',
            field=models.CharField(choices=[('REMOTE_START_TRANSACTION', 'Remote start transaction'), ('REMOTE_STOP_TRANSACTION', 'Remote stop transaction')], max_length=50, verbose_name='Command'),
        ),
    ]
