# Generated by Django 5.0.3 on 2024-04-03 16:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_manufacturer_alter_frontendtranslation_id_carmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], max_length=255, verbose_name='Type')),
                ('icon', models.ImageField(upload_to='icons/%Y/%m', verbose_name='Icon')),
                ('max_voltage', models.IntegerField(verbose_name='Max Voltage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ico_code', models.CharField(max_length=10, verbose_name='ISO code')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('telegram_link', models.CharField(max_length=255, verbose_name='Telegram Link')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.AlterModelOptions(
            name='usercar',
            options={'verbose_name': 'User Car', 'verbose_name_plural': 'User Cars'},
        ),
        migrations.AlterField(
            model_name='usercar',
            name='state_number_type',
            field=models.IntegerField(blank=True, choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('LEGAL', 'LEGAL'), ('DIPLOMATIC', 'DIPLOMATIC'), ('OON', 'OON'), ('InternationalResident', 'InternationalResident'), ('InternationalOrganization', 'InternationalOrganization')], null=True, verbose_name='Type of State Number'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='connector_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.connectiontype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['-id'],
            },
        ),
    ]
