# Generated by Django 5.0.3 on 2024-04-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_connectiontype_country_support_alter_usercar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='common.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='common.country', verbose_name='Country'),
        ),
        migrations.RemoveField(
            model_name='usercar',
            name='connector_type',
        ),
        migrations.AddField(
            model_name='usercar',
            name='connector_type',
            field=models.ManyToManyField(blank=True, related_name='car_connector_types', to='common.connectiontype', verbose_name='Connector Types'),
        ),
    ]
