# Generated by Django 5.0.3 on 2024-04-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_district_region_alter_region_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiontype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectiontype",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectiontype",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectiontype",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="frontendtranslation",
            name="text_en",
            field=models.CharField(max_length=1024, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="frontendtranslation",
            name="text_ru",
            field=models.CharField(max_length=1024, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="frontendtranslation",
            name="text_uz",
            field=models.CharField(max_length=1024, null=True, verbose_name="Text"),
        ),
    ]
