# Generated by Django 5.0.3 on 2024-04-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_connectiontype_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercar",
            name="state_number_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INDIVIDUAL", "INDIVIDUAL"),
                    ("LEGAL", "LEGAL"),
                    ("DIPLOMATIC", "DIPLOMATIC"),
                    ("OON", "OON"),
                    ("InternationalResident", "InternationalResident"),
                    ("InternationalOrganization", "InternationalOrganization"),
                ],
                null=True,
                verbose_name="Type of State Number",
            ),
        ),
    ]
