# Generated by Django 5.0.3 on 2024-04-17 00:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_alter_usercar_state_number_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercar",
            unique_together={("user", "vin")},
        ),
    ]
