# Generated by Django 5.0.3 on 2024-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_usercar_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price for 1 kwt of electricity')),
                ('user_minimum_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price for 1 kwt of electricity')),
                ('ios_version', models.CharField(max_length=20)),
                ('android_version', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'MainSettings',
                'verbose_name_plural': 'MainSettings',
            },
        ),
    ]
