# Generated by Django 5.0.3 on 2024-04-18 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0009_alter_chargecommand_limited_money_and_more'),
        ('common', '0008_mainsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='user_minimum_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='User minimum balance'),
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='chargers.location', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Location',
                'verbose_name_plural': 'Saved Locations',
            },
        ),
    ]
