# Generated by Django 5.0.3 on 2024-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_mainsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='user_minimum_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='User minimum balance'),
        ),
    ]
