# Generated by Django 5.0.3 on 2024-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_appealtypelist_userappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='help_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Help Email'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='help_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Help Phone Number'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='help_telegram_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Help Telegram Link'),
        ),
    ]
