# Generated by Django 5.0.3 on 2024-04-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0010_alter_chargingtransaction_battery_percent_on_end'),
        ('common', '0011_mainsettings_help_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappeal',
            name='charge_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='chargers.chargepoint', verbose_name='Charge Point'),
        ),
    ]
