# Generated by Django 5.0.3 on 2024-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_savedlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercar',
            unique_together=set(),
        ),
    ]
