# Generated by Django 5.0.3 on 2024-05-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_usercar_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
