# Generated by Django 5.0.3 on 2024-05-05 08:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_staticpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="content_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="content_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
    ]
