# Generated by Django 5.0.3 on 2024-06-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_staticpage_content_en_staticpage_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='price',
        ),
    ]
