# Generated by Django 5.0.3 on 2024-05-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(choices=[('payment', 'Payment'), ('charge', 'Charging')], max_length=20, verbose_name='Action')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'All Transaction History',
                'verbose_name_plural': 'All Transaction History',
                'db_table': 'all_transaction_postgres_view',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),

        migrations.RunSQL(
            f"""
                DROP VIEW IF EXISTS all_transaction_postgres_view;

                CREATE VIEW all_transaction_postgres_view AS
                SELECT
                    id,
                    created_at,
                    updated_at,
                    'charge' as action,
                    user_id,
                    total_price as amount
                FROM public."chargers_chargingtransaction"
                    WHERE status='FINISHED'

                UNION ALL

                SELECT
                    id,
                    created_at,
                    updated_at,
                    'payment' AS action,
                    user_id,
                    amount
                FROM public."Transaction"
                    WHERE status='accepted';
                """
        )

    ]




