# Generated by Django 5.0.3 on 2024-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS all_transaction_postgres_view;

            CREATE VIEW all_transaction_postgres_view AS
            SELECT
                id,
                created_at,
                updated_at,
                'charge' as action,
                user_id,
                total_price as amount
            FROM public."chargers_chargingtransaction"
                WHERE status='FINISHED'
                
            UNION ALL
                    
            SELECT
                id,
                created_at,
                updated_at,
                'payment' AS action,
                user_id,
                amount
            FROM public."Transaction"
                WHERE status='confirmed';
            """
        ),
    ]
