# Generated by Django 5.0.3 on 2024-04-03 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], max_length=16, verbose_name='Status')),
                ('card_number', models.CharField(max_length=32, verbose_name='Card number')),
                ('cid', models.CharField(max_length=255, verbose_name='Card Id')),
                ('expire_date', models.CharField(max_length=255, verbose_name='Expire Date')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
                ('balance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Balance')),
                ('vendor', models.CharField(blank=True, choices=[('humo', 'Humo'), ('uzcard', 'Uzcard')], max_length=32, null=True, verbose_name='Vendor')),
                ('processing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Processing')),
                ('bank_id', models.CharField(blank=True, null=True, verbose_name='Bank id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserCard',
                'verbose_name_plural': 'UserCards',
                'db_table': 'UserCard',
                'ordering': ('card_number',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=32, verbose_name='Status')),
                ('remote_id', models.CharField(max_length=255, null=True, verbose_name='Remote id')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='TAX Amount')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('CLICK', 'CLICK'), ('PAYME', 'PAYME'), ('UZUM', 'UZUM')], verbose_name='Payment Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.usercard', verbose_name='Card id')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
                'ordering': ('remote_id',),
            },
        ),
    ]
