# Generated by Django 5.0.3 on 2024-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], max_length=32, verbose_name='Status'),
        ),
    ]
