# Generated by Django 5.0.3 on 2024-04-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('CLICK', 'CLICK'), ('PAYME', 'PAYME'), ('UZUM', 'UZUM')], max_length=50, verbose_name='Payment type')),
                ('request_headers', models.JSONField(null=True, verbose_name='Request Headers')),
                ('request_body', models.JSONField(null=True, verbose_name='Request Headers')),
                ('response_headers', models.JSONField(null=True, verbose_name='Request Headers')),
                ('response_body', models.JSONField(null=True, verbose_name='Request Headers')),
                ('response_status_code', models.PositiveSmallIntegerField(null=True, verbose_name='Response status code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
