# Generated by Django 5.0.3 on 2024-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_merchantrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='request_body',
            field=models.TextField(null=True, verbose_name='Request Headers'),
        ),
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='request_headers',
            field=models.TextField(null=True, verbose_name='Request Headers'),
        ),
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='response_body',
            field=models.TextField(null=True, verbose_name='Request Headers'),
        ),
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='response_headers',
            field=models.TextField(null=True, verbose_name='Request Headers'),
        ),
    ]
