# Generated by Django 5.0.3 on 2024-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_merchantrequestlog_request_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='request_body',
            field=models.TextField(null=True, verbose_name='Request Body'),
        ),
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='response_body',
            field=models.TextField(null=True, verbose_name='Response Body'),
        ),
        migrations.AlterField(
            model_name='merchantrequestlog',
            name='response_headers',
            field=models.TextField(null=True, verbose_name='Response Headers'),
        ),
    ]
