# Generated by Django 5.0.3 on 2024-04-23 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_merchantrequestlog_method_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('user', 'card_number', 'expire_date')},
        ),
    ]
