# Generated by Django 5.0.3 on 2024-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_usercard_is_deleted_alter_usercard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='cid',
            field=models.TextField(verbose_name='Card Id'),
        ),
    ]
