# Generated by Django 5.0.3 on 2024-04-23 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_usercard_cid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('user', 'card_number', 'expire_date', 'status')},
        ),
    ]
