# Generated by Django 5.0.3 on 2024-04-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_usercard_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='is_deleted',
        ),
    ]
