# Generated by Django 5.0.3 on 2024-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_usercard_balance_remove_usercard_bank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='vendor',
            field=models.CharField(blank=True, choices=[('humo', 'Humo'), ('uzcard', 'Uzcard')], max_length=32, null=True, verbose_name='Vendor'),
        ),
    ]
