# Generated by Django 5.0.3 on 2024-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0017_usercard_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_notification_sent",
            field=models.BooleanField(
                default=False, verbose_name="Is notification sent"
            ),
        ),
    ]
