on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
          cd /var/www/afsona.transitgroup.uz
          source venv/bin/activate
          git pull origin main
          pip3 install -r requirements/production.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo /bin/systemctl restart afsona-gunicorn.service
