on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: /var/www/afsona.transitgroup.uz

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
          cd /var/www/afsona.transitgroup.uz
          source venv/bin/activate
          git pull origin main

    - name: Install dependencies
      run: pip3 install -r requirements/production.txt

    - name: Run migrations
      run: python3 manage.py migrate

    - name: Restart service
      run: sudo /bin/systemctl restart afsona-gunicorn.service
