on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
          whoami
          cd /var/www/afsona.transitgroup.uz
          git pull origin main
          sudo /bin/systemctl restart afsona-gunicorn.service
